export const LIMITS = {
  // File upload limits
  MAX_FILE_SIZE: 5 * 1024 * 1024, // 5MB
  MAX_IMAGES_PER_ORDER: 10,
  MAX_INSPIRATION_IMAGES: 5,
  MAX_QC_ISSUE_PHOTOS: 5,

  // Pagination
  DEFAULT_PAGE_LIMIT: 20,
  MAX_PAGE_LIMIT: 100,

  // Rate limits
  MAX_LOGIN_ATTEMPTS: 5,
  LOGIN_LOCKOUT_MINUTES: 15,
  MAX_ACTIVATION_CODE_ATTEMPTS: 3,

  // Subscription
  MAX_RETRY_ATTEMPTS: 3,
  GRACE_PERIOD_DAYS: 7,

  // Order
  MAX_ITEMS_PER_ORDER: 10,
  MAX_ACCESSORIES_PER_ORDER: 20,

  // Tailor
  DEFAULT_TAILOR_CAPACITY: 10,
  MAX_TAILOR_CAPACITY: 50,
  PROBATION_JOBS_COUNT: 5,
  MAX_MISSED_DEADLINES: 3,

  // Session
  SESSION_TTL_DAYS: 30,
  MAX_SESSIONS_PER_USER: 5,

  // Text lengths
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_NOTES_LENGTH: 500,
  MAX_NAME_LENGTH: 100,
  MAX_ADDRESS_LENGTH: 500,

  // Measurements
  MIN_MEASUREMENT_CM: 1,
  MAX_MEASUREMENT_CM: 500,
  MIN_WEIGHT_KG: 20,
  MAX_WEIGHT_KG: 300,
  MIN_HEIGHT_CM: 100,
  MAX_HEIGHT_CM: 250,
};

export default LIMITS;
